### ISSUE TITLE
No textures, OSX  Compiled with 10.6 /w gcc 4.2.1-apple

### ISSUE THREAD

**Issue by JoshuaPettus** [zaps166/NFSIISE#30]
So I undid 481f650,  and compiled.  However I'm getting no textures in game

The game says I'm using
  Wrapper v1.2.0
  Game    v1.1.2
  OpenGL  2

These are all up to date, correct?

![screen shot 2017-05-21 at 8 46 37 am](https://cloud.githubusercontent.com/assets/5043172/26284169/07d33e80-3e03-11e7-939e-205e477e93bc.png)

**Comment by zaps166** [comment]
Hmm, I didn't test it on macOS yet :) This is bug in new GL2 renderer, I forgot to add `-DOPENGL1X` macro for macOS. Could you add it and try again?

**Comment by JoshuaPettus** [comment]
Yup it works now.  Will it be possible to get the new GL2 render to work?

**Comment by zaps166** [comment]
> Will it be possible to get the new GL2 render to work?

It already works on my Linux with NVIDIA GPU and on my Android phone 😃 But it needs optimization and bugfixes and tests for more platforms.

**Comment by JoshuaPettus** [comment]
Thanks!

**Comment by zaps166** [comment]
Can't reproduce this bug, could you test again ?

**Comment by JoshuaPettus** [comment]
Sorry, i've been totally busy last week and will be this week.  I'll try to remember to find the time.

**Comment by zaps166** [comment]
Ok!

**Comment by JoshuaPettus** [comment]
sorry for the wait, I finally got to compile it again.  I'm afraid gl2 still has the same problem

**Comment by zaps166** [comment]
Hmm, weird...

Could you remove this line (https://github.com/zaps166/NFSIISE/blob/cd52693267ab272de9ea0be368f2ad9538c48554/src/Glide2x/OpenGL2.c#L143) and try again (textures will be corrupted, but it is good point to test)?

**Comment by JoshuaPettus** [comment]
Yeah, there is a little bit of texture distortion. particularly with the hud, but they do show up

**Comment by zaps166** [comment]
Do you have AMD Radeon GPU ?

**Comment by JoshuaPettus** [comment]
Nope, but my laptop has a crappy Intel Graphics as well as a crappy Nvidia Gforce 320M.  To be honest I have no idea which one it is using when NFS2SE launches.  (I'm starting to think the intel one).  In that case I should try it on my hackentosh which has a proper NVIDIA GTX 960

**Comment by zaps166** [comment]
I've tested on 3rd gen (HD 4000?) and GTX 1080 on macOS 10.12.4 and it worked OK, hmmm, weird 😄 I know that conditions in shaders are not good, but it simplifies everything and works on other machines...

Which OS version do you have and is it still GCC 4.2.1 (I use Apple clang 8)?

**Comment by zaps166** [comment]
In my case it also works on VirtualBox with textures (GL2): [NFSIISE-GL2-VirtualBox-cd52693.mkv.zip](https://github.com/zaps166/NFSIISE/files/1064769/NFSIISE-GL2-VirtualBox-cd52693.mkv.zip)

You can also test my binary which I used to create a Video ([nfs2se-macOS-cd52693.zip](https://github.com/zaps166/NFSIISE/files/1064780/nfs2se-macOS-cd52693.zip)) :)

---

If you have problems with opening YUV444/H.264 video, you can use [QMPlay2](https://github.com/zaps166/QMPlay2/releases) (also available DMG for macOS).

**Comment by JoshuaPettus** [comment]
Ahh, It seems to work on 10.12 but not any earlier.  My guess is it's an OpenGl issue with the older OSs.  In that case we should have 2 versions one Gl1 10.6+ and one Gl2 10.12+

**Comment by zaps166** [comment]
Thanks for testing. I've made a patch (GitHub closes issue automatically). Could you test it now (& reopen if problem still exists)?

Also you can upload screenshot with this scene (brightness: 6): <img width="640" alt="nfsiise-last_resort_view" src="https://user-images.githubusercontent.com/6239090/27002749-3b9bd56a-4de9-11e7-8c7b-eb4eee51e4b4.png">

**Comment by JoshuaPettus** [comment]
Sorry for the delay
 I tried compiling it again,  I got:
`Building release for macOS... Wrapper.c:277:7: error: use of undeclared identifier 'shaderError'
        if (!shaderError) // Workaround: Game freezes in this case`

Also another thing, Maybe for the osx build it would be better to use -framework SDL2 as oppose to -lSDL2.  Not that the latter wont work if you install SDL2 though macports or homebrew (either is necessary to install yasm)  But it might be better to use the native SDL2.framework at runtime.  Just a thought, It's what I do for the app.

Also i can't seem to reopen the ticket

**Comment by zaps166** [comment]
> I tried compiling it again, I got

You're trying to compile using OpenGL 1, fixed: ea296e859bfc81bde75443afa8d4c32cd2f53484

---

How do you compile SDL2 32-bit? Is it available from homebrew?

---

Do you have textures for OpenGL 2 :) ?

**Comment by JoshuaPettus** [comment]
Ah, good thing I do things wrong to catch this stuff :)

I don't use homebrew myself, I have a strong preference for macports.  To get 32 bit SDL2 you  just use port libsdl2 +universal.  But again, it's better to use the sdl2.framework for distribution purposes as it supports 10.5+ and a dylib will be limited to the OS it was compiled for and newer.

Yup! That fixed the textures,  even if it's compiled with the old apple gcc!

**Comment by zaps166** [comment]
The sky looks weird on this screenshot, hmmm. Could you upload the same scene as in my previous screenshot?

---

I'll try the official DMG. I always build SDL2 with env: `CC="clang -m32"` :)

**Comment by JoshuaPettus** [comment]
Well tell you what, I created a new .dmg with a new 1.3.2 app

It includes executables for both gl1 and gl2, and it asks the user at launch which version of opengl they want to use.  It also gives them the option to make the selection permanent by creating an empty file named "gl1" or "gl2" in the Application data folder and checks for either prior to asking the user.

https://www.dropbox.com/s/58tw3p68fblgdop/nfs2se-OSX-10.6-v1.3.2.dmg?dl=0

**Comment by zaps166** [comment]
Thanks for testing!

---

Could you simplify data copying - if I don't have CD I would open a destination directory (for `fedata` and `gamedata`).

Is it possible to compile for OSX 10.5 if SDL2 framework is capable with it (`SDL2-2.0.5.dmg (Intel 10.5+)`)?

IMHO if GL2 works properly, GL1 is not needed especially on Mac 😄 

The version is 1.2.3, but I'll bump it soon and release.

**Comment by JoshuaPettus** [comment]
Well I'm thinking about lousy crappy video cards,  or some of the not so common amd cards that you and I don't have. 

If you don't have a CD then you should at least have a cd image which you would just mount and would still work.

As for 10.5...I wouldn't worry about it...There never were a lot of 10.5 intel macs. I could set -mmacosx-version-min=10.5 and -isysvol=/Developer/MacOSX-10.5.sdk (or whatever) on the 10.6 VM (It would never work on a modern mac).  It can be a pain cross compiling, and apple just makes it harder and harder the later you get.

**Comment by zaps166** [comment]
No, 10.5 isn't necessary, I wanted to know if it is possible on new toolchain 😄

> Well I'm thinking about lousy crappy video cards, or some of the not so common amd cards that you and I don't have.

Are there any Macs with OSX 10.6 which are not GL2 capable (http://arek.bdmonkeys.net/GLInfo/GLInfo_1068.html) except this one old Intel?

---

> If you don't have a CD then you should at least have a cd image which you would just mount (just double click on OSX) and would still work.

I have unpacked data on external HDD, so for me this method is not convenient 😄 If possible - you can add a button which creates (if necessary) and opens a destination directory :)

**Comment by JoshuaPettus** [comment]
Hmm, I'll have a look at the script.  I think that should be very doable, and have it somewhat self correcting (caps to lowercase, and extra data files).

Regarding OpenGL to be honest, I have no idea.  It doesn't hurt, I suppose, I made Gl2 the first choice... If you want to stick multiple executables in, then it's not a problem.  (Maybe as a future project you could have a software rendered version, with the classic cockpits).

**Comment by zaps166** [comment]
> Maybe as a future project you could have a software rendered version, with the classic cockpits

Nope, this was other executable, so it means that I must do it from beginning 😄 But maybe there is another way for doing it, e.g. put cockpit view into GL version.

---

Ok, so do a GL2 version as default :)

**Comment by JoshuaPettus** [comment]
> e.g. put cockpit view into GL version.
That would be fantastic. It would be like having your cake and eating it! :) 

I updated the package, same link as before.  Now with a manual install option. It will clean up the folders after you copy and press "ok".  Otherwise if you click "never mind!", then it doesn't clean up, and won't count for case sensitive file systems.  But in that case, it will just open up the install dialogs again.

https://www.dropbox.com/s/58tw3p68fblgdop/nfs2se-OSX-10.6-v1.3.2.dmg?dl=0
